version: '3'

services:
  bot:
    container_name: stare-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.data:/usr/src/app/.data
    env_file:
      - .env
    tty: true
    stdin_open: true