[versions]
jda = "5.0.0-beta.24"
ormlite = "6.1"
jdbc-sqlite = "3.46.0.0"
json = "20240303"
slf4j = "2.0.13"
lombok = "1.18.34"
buildConfig = "5.3.5"
jcp = "7.1.2"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
ormlite = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }
jdbc-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "jdbc-sqlite" }
json = { module = "org.json:json", version.ref = "json" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jcp = { module = "com.igormaznitsa:jcp", version.ref = "jcp"}
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig"}