[versions]
jda = "5.0.0-beta.24"
ormlite = "6.1"
jdbc-sqlite = "3.45.3.0"
json = "20240303"
slf4j = "2.0.13"
lombok = "8.6"
buildConfig = "5.3.5"
manifold-preprocessor = "2024.1.16"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
ormlite = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }
jdbc-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "jdbc-sqlite" }
json = { module = "org.json:json", version.ref = "json" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
manifold-preprocessor = { module = "systems.manifold:manifold-preprocessor", version.ref = "manifold-preprocessor"}

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok"}
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig"}