name: Check

on:
  push:
    branches:
      - "master"
      - "dev"

  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    container: gradle:8.7.0-jdk21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: gradle check --no-daemon