name: Check

on:
  workflow_call:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 22
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Check with Gradle
        run: ./gradlew check