name: Check

on:
  push:
    branches:
      - "master"
      - "dev"

  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  test:
    name: Run code verification
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run checks
        uses: docker/build-push-action@v5
        with:
          context: Check.Dockerfile
          push: false
          platforms: linux/amd64
          tags: mintdaniel42/prncsdiscordbot:check